apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: artpulse-production-wildcard
  namespace: artpulse
spec:
  secretName: artpulse-production-wildcard-tls
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
  dnsNames:
    - "api.wearetheartmakers.com"
    - "*.wearetheartmakers.com"
