apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-staging
  namespace: cert-manager
type: Opaque
stringData:
  api-token: "replace-with-cloudflare-staging-api-token"
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-production
  namespace: cert-manager
type: Opaque
stringData:
  api-token: "replace-with-cloudflare-production-api-token"
