apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: artpulse-production
  namespace: artpulse
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "4m"
    nginx.ingress.kubernetes.io/limit-rps: "40"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "4"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.wearetheartmakers.com
      secretName: artpulse-production-wildcard-tls
  rules:
    - host: api.wearetheartmakers.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: artpulse
                port:
                  number: 80
